# Generated by Django 3.2 on 2021-05-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_cathegory_cathegory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathegory',
            name='cathegory',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cathegory',
            field=models.ManyToManyField(blank=True, through='news.PostCathegory', to='news.Cathegory'),
        ),
    ]
