# Generated by Django 3.2 on 2021-05-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_cathegory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathegory',
            name='cathegory',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
